name: build-alpine

on:
  push:
    branches: [ 'main' ]
    paths: [ 'dockerfiles/alpine.Dockerfile' ]
  workflow_dispatch:

jobs:
  build_docker:
    runs-on: ubuntu-latest

    steps:
      - name: 设置QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: 设置Docker BuildX
        uses: docker/setup-buildx-action@v3
    
      - name: 登录到DockerHub
        uses: docker/login-action@v3
        with:
          username: syscc
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 构建并推送
        uses: docker/build-push-action@v6
        with:
          file: dockerfiles/alpine.Dockerfile
          push: true
          tags: syscc/openlistsync:not-for-use-alpine
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/386,linux/arm/v6,linux/s390x,linux/ppc64le
